export const KEYSTOKEEPDPE = [
  // 'Nombre_niveau_logement',
  // 'Type_installation_ECS_(général)',
  'N°_étage_appartement',
  'Date_établissement_DPE',
  'N°DPE',
  // 'Logement_traversant_(0/1)',
  // 'Modèle_DPE',
  'Surface_habitable_logement',
  'Type_bâtiment',
  // 'Zone_climatique_',
  // 'Version_DPE',
  '_geopoint',
  'date_etablissement_dpe',
  // 'annee_construction',
  // 'surface_thermique_lot',
  'Etiquette_GES',
  'Etiquette_DPE',
  'classe_consommation_energie',
  'classe_estimation_ges',
];
